default_agent: agentcore_deployment
agents:
  agentcore_deployment:
    name: agentcore_deployment
    entrypoint: agentcore_deployment.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::313806797257:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-992f8f5be7
      execution_role_auto_create: false
      account: '313806797257'
      region: us-east-1
      ecr_repository: 313806797257.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_deployment
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_deployment-hQDE9gD1Pp
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:313806797257:runtime/agentcore_deployment-hQDE9gD1Pp
      agent_session_id: 737486e6-e959-49c3-8840-6a60a16609b8
    codebuild:
      project_name: bedrock-agentcore-agentcore_deployment-builder
      execution_role: arn:aws:iam::313806797257:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-992f8f5be7
      source_bucket: bedrock-agentcore-codebuild-sources-313806797257-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: agentcore_deployment_mem-x1iBrUA1NY
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:313806797257:memory/agentcore_deployment_mem-x1iBrUA1NY
      memory_name: agentcore_deployment_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
